---
deployment:
  tasks:
    - export PATH=/opt/cpanel/composer/bin:$PATH
    - /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader
    - php artisan migrate --force
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
    - php artisan storage:link
    - chown -R $USER:$USER storage bootstrap/cache
    - chmod -R 775 storage bootstrap/cache
